language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "alexandrtel"
    token:
      secure: $SONAR_TOKEN

script:
  - qmake
  - make
  - /home/travis/build/AlexandrTel/Lab.3/test

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make all
  - sonar-scanner

cache:
  directories:
  - '$HOME/.sonar/cache'

 
notifications:
  email: false
