language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - qmake
  - make
  - ./tests/tests

os:
  - windows

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"

notifications:
  email: false
